# Generated by Django 6.0 on 2026-01-05 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trail_status', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='last_checked_at',
            field=models.DateTimeField(blank=True, help_text='最後に各サイトの更新有無を確認した日時', null=True, verbose_name='最終巡回日時'),
        ),
    ]
