# Generated by Django 6.0 on 2026-01-09 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trail_status', '0002_datasource_last_checked_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mountaingroup',
            name='area',
            field=models.CharField(choices=[('OKUTAMA', '奥多摩'), ('TANZAWA', '丹沢'), ('TAKAO', '高尾・奥高尾'), ('HAKONE', '箱根'), ('OKUMUSASHI', '奥武蔵'), ('OKUCHICHIBU', '奥秩父'), ('DAIBOSATSU', '大菩薩連嶺'), ('SAGAMIKO', '相模湖')], max_length=20, verbose_name='山域'),
        ),
        migrations.AlterField(
            model_name='trailcondition',
            name='area',
            field=models.CharField(choices=[('OKUTAMA', '奥多摩'), ('TANZAWA', '丹沢'), ('TAKAO', '高尾・奥高尾'), ('HAKONE', '箱根'), ('OKUMUSASHI', '奥武蔵'), ('OKUCHICHIBU', '奥秩父'), ('DAIBOSATSU', '大菩薩連嶺'), ('SAGAMIKO', '相模湖')], max_length=20, verbose_name='山域'),
        ),
        migrations.AlterField(
            model_name='trailcondition',
            name='status',
            field=models.CharField(choices=[('CLOSURE', '🚧 通行止め'), ('HAZARD', '⚠️ 通行注意'), ('CLEAR', '✅ 通行可能'), ('ANIMAL', '🐻 動物出没'), ('WEATHER', '🌧️ 気象警報'), ('FACILITY', '🏠 施設情報'), ('WATER', '💧 水場状況'), ('SNOW', '❄️ 積雪'), ('OTHER', '📝 その他')], default='CLOSURE', max_length=20, verbose_name='状況種別'),
        ),
    ]
