# Generated by Django 6.0.1 on 2026-01-18 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trail_status', '0003_alter_mountaingroup_area_alter_trailcondition_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='機関名'),
        ),
    ]
