# Generated by Django 6.0.1 on 2026-02-02 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trail_status', '0004_alter_datasource_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='description',
            field=models.TextField(blank=True, help_text='情報源一覧ページに表示される文章', verbose_name='詳細説明'),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='data_format',
            field=models.CharField(choices=[('WEB', 'Webページ'), ('BLOG', '巡視ブログ')], default='WEB', max_length=50, verbose_name='データ形式'),
        ),
    ]
