# Generated by Django 6.0.1 on 2026-02-11 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trail_status', '0005_datasource_description_alter_datasource_data_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='area_name',
            field=models.CharField(blank=True, choices=[('OKUTAMA', '奥多摩'), ('TANZAWA', '丹沢'), ('TAKAO', '高尾・奥高尾'), ('HAKONE', '箱根'), ('OKUMUSASHI', '奥武蔵'), ('OKUCHICHIBU', '奥秩父'), ('DAIBOSATSU', '大菩薩連嶺'), ('SAGAMIKO', '相模湖')], default='', help_text='巡視ブログのエリア名分類用に使用', max_length=20, verbose_name='山域'),
        ),
        migrations.AlterField(
            model_name='trailcondition',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trail_status.datasource', verbose_name='情報源'),
        ),
        migrations.AlterField(
            model_name='trailcondition',
            name='url1',
            field=models.URLField(max_length=500, verbose_name='情報源URL'),
        ),
        migrations.CreateModel(
            name='BlogFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='記事のタイトル')),
                ('summary', models.TextField(max_length=200, verbose_name='記事の冒頭')),
                ('url', models.URLField(max_length=500, verbose_name='記事へのリンクURL')),
                ('published_at', models.DateTimeField(verbose_name='投稿日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('disabled', models.BooleanField(default=False, help_text='[使用例] 誤情報だった場合ほか', verbose_name='情報の無効化フラグ')),
                ('source', models.ForeignKey(limit_choices_to={'data_format': 'BLOG'}, on_delete=django.db.models.deletion.PROTECT, to='trail_status.datasource', verbose_name='情報源')),
            ],
            options={
                'verbose_name': '巡回ブログ',
                'verbose_name_plural': '巡回ブログ',
                'ordering': ['-published_at'],
            },
        ),
    ]
