# Generated by Django 6.0.3 on 2026-04-27 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trail_status', '0006_datasource_area_name_alter_trailcondition_source_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trailcondition',
            old_name='reference_URL',
            new_name='reference_url',
        ),
    ]
