# Generated by Django 6.0 on 2026-01-03 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "trail_status",
            "0007_trailcondition_ai_config_trailcondition_ai_model_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="datasource",
            name="content_hash",
            field=models.CharField(
                blank=True,
                help_text="スクレイピング内容のハッシュ値（変更検知用）",
                max_length=64,
                verbose_name="コンテンツハッシュ",
            ),
        ),
        migrations.AddField(
            model_name="datasource",
            name="last_scraped_at",
            field=models.DateTimeField(
                blank=True,
                help_text="最後にコンテンツを取得した日時",
                null=True,
                verbose_name="最終スクレイピング日時",
            ),
        ),
    ]
