# Generated by Django 6.0.5 on 2026-06-27 08:01

from django.db import migrations, models


def set_scraped_at(apps, schema_editor):
    TrailCondition = apps.get_model("trail_status", "TrailCondition")
    for obj in TrailCondition.objects.all():
        TrailCondition.objects.filter(pk=obj.pk).update(synced_at=obj.updated_at)


class Migration(migrations.Migration):
    dependencies = [
        ("trail_status", "0007_rename_reference_url_trailcondition_reference_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="trailcondition",
            name="synced_at",
            field=models.DateTimeField(verbose_name="バッチによる自動更新日時", null=True),
        ),
        migrations.RunPython(set_scraped_at),
    ]
