# Generated by Django 6.0 on 2026-01-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trail_status', '0008_datasource_content_hash_datasource_last_scraped_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailcondition',
            name='reported_at',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='報告日'),
        ),
    ]
