"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/

デプロイチェックリスト：
https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/
"""

from .base import *

# ======================================================


# 本番環境用の設定
ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "trail-info.jp,www.trail-info.jp").split(",")
# この設定により、Cloudflare が付与する X-Forwarded-Proto: https ヘッダーを見て「実際は HTTPS だ」と判断できます。これがないと: request.is_secure() が常に False / CSRF 検証が失敗する可能性 / リダイレクトURLが http:// になる

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_TRUSTED_ORIGINS = [
    "https://trail-info.jp",
    "https://www.trail-info.jp",
]
CORS_ALLOWED_ORIGINS = [
    "https://trail-info.jp",
    "https://www.trail-info.jp",
]
