name: Test

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Build
        run: docker compose build

      - name: Create .env.local
        run: echo "${{ secrets.ENV_LOCAL }}" > .env.local

      - name: Up
        run: docker compose up -d --wait web db

      - name: Check containers
        run: docker compose ps
        
      - name: Memory check
        run: docker stats --no-stream

      - name: Execute test
        run: docker compose exec web uv run pytest

      - name: Memory check
        run: docker stats --no-stream
